/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void calculatorTestOne() {
        Calculator classUnderTest = new Calculator();
        assertThrows(ArithmeticException.class, () -> classUnderTest.solve("foo / 30 + 7"));
    }

    @Test void calculatorTestTwo() {
        Calculator classUnderTest = new Calculator();
        assertEquals(50, classUnderTest.solve("10 + 20 * 2"));
    }
}
