/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public static void main(String[] args) {
        System.out.println(new Calculator().solve("10 + 20 * 2 "));
    }
}
